# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MOYO' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MOYO
#
pod 'Alamofire', '<= 4.7.2'
pod 'KeychainSwift'
pod 'SwiftCharts', '<= 0.6.5'
pod 'KRProgressHUD', '<= 3.2.2'
pod 'SwiftyJSON', '<= 4.2.0'
pod 'iOSDropDown'


post_install do |installer|
 installer.pods_project.targets.each do |target|
  target.build_configurations.each do |config|
   config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
  end
 end
end
end
